MVC_Camp/Controllers/ChartController.cs
using MVC_Camp.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.Ajax.Utilities;

namespace MVC_Camp.Controllers
{
    public class ChartController : Controller
    {
        private HeadingManager hm = new HeadingManager(new EfHeadingDal());
        private CategoryManager cm = new CategoryManager(new EfCategoryDal());

        // GET: Chart
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult CategoryChart()
        {
            return Json(BlogList(), JsonRequestBehavior.AllowGet);
        }


        public List<CategoryClass> BlogList()
        {
            List<CategoryClass> ct = new List<CategoryClass>();

            var values = cm.GetList();
            foreach (var item in values)
            {
                var num = hm.GetHeadingCountInCategory(item.CategoryName);
                ct.Add(new CategoryClass() { CategoryName = item.CategoryName, CategoryCount = num });
            }

            return ct;
        }
    }
}

MVC_Camp/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("CategoryChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });

                    console.log(result);
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'CategoryName');
            data.addColumn('number', 'CategoryCount');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.CategoryName, obj.CategoryCount]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Ürün - Stok Grafiği",
                width: 1000,
                height: 800,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
    <p>@ViewBag.c</p>
</body>
</html>