MVC_Camp/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;

namespace MVC_Camp.Controllers
{

    public class ContactController : Controller
    {
        Context context = new Context();

        private DraftMessageManager dfm = new DraftMessageManager(new EfDraftMessageDal());
        ContactManager cm = new ContactManager(new EfContactDal());
        MessageManager mm = new MessageManager(new EfMessageDal());
        ContactValidator cv = new ContactValidator();
        
        public ActionResult Index()
        {
            var contactvalues = cm.GetList();
            return View(contactvalues);
        }

        public ActionResult GetContactDetails(int id)
        {
            var contactValue = cm.GetById(id);
            if (contactValue.IsRead == false)
            {
                contactValue.IsRead = true;
                cm.ContactUpdate(contactValue);
            }
            return View(contactValue);
        }

        public PartialViewResult ContactLeftPart()
        {
            ViewBag.ContactMailCount = cm.GetUnread().Count();
            ViewBag.MailCount = mm.GetListInbox("aalaca.33@gmail.com").Count();
            ViewBag.SentMailCount = mm.GetListSentBox("aalaca.33@gmail.com").Count();
            ViewBag.DraftMailCount = dfm.GetList("aalaca.33@gmail.com").Count();
            return PartialView();
        }
    }
}

MVC_Camp/Controllers/DraftController.cs
using System;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System.Web.Mvc;
using BusinessLayer.ValidationRules;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace MVC_Camp.Controllers
{
    public class DraftController : Controller
    {
        private DraftMessageManager dfm = new DraftMessageManager(new EfDraftMessageDal());
        DraftMessageValidator messageValidator = new DraftMessageValidator();

        public ActionResult Index()
        {
            var draftMessageValues = dfm.GetList("aalaca.33@gmail.com");
            return View(draftMessageValues);
        }

        [HttpPost]
        public ActionResult AddDraftMessage(DraftMessage message)
        {
            message.SentDate = DateTime.Now;
            message.SenderMail = "admin@gmail.com";
            dfm.DraftMessageAddBl(message);

            return RedirectToAction("Index");
        }

        public ActionResult GetMessageDetails(int id)
        {
            var messageValues = dfm.GetById(id);
            return View(messageValues);
        }
    }
}

MVC_Camp/Controllers/MessageController.cs
using System;
using System.Linq;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System.Web.Mvc;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace MVC_Camp.Controllers
{
    public class MessageController : Controller
    {
        MessageManager mm = new MessageManager(new EfMessageDal());
        DraftMessageManager dfm = new DraftMessageManager(new EfDraftMessageDal());
        MessageValidator messageValidator = new MessageValidator();

        DraftController df = new DraftController();


        public ActionResult Inbox(string p)
        {
            string mail = (string)Session["WriterMail"];
            var messageList = mm.GetListInbox(mail);
            return View(messageList);
        }
        public ActionResult SentBox()
        {
            var messageList = mm.GetListSentBox("aalaca.33@gmail.com");
            return View(messageList);
        }

        [HttpGet]
        public ActionResult NewMessage()
        {
            return View();
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult NewMessage(Message message, string button)
        {

            ValidationResult results = messageValidator.Validate(message);
            if (results.IsValid)
            {
                if (button == "draft")
                {
                    DraftMessage draftMessage = new DraftMessage();
                    draftMessage.ReceiverMail = message.ReceiverMail;
                    draftMessage.Subject = message.Subject;
                    draftMessage.MessageContent = message.MessageContent;
                    df.AddDraftMessage(draftMessage);

                    return RedirectToAction("Index", "Draft");
                }
                else if (button == "send")
                {
                    message.SentDate = DateTime.Now;
                    message.SenderMail = "admin@gmail.com";
                    mm.MessageAddBl(message);
                    return RedirectToAction("SentBox");
                }
            }
            else
            {
                foreach (var error in results.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult GetInboxMessageDetails(int id)
        {
            var messageValue = mm.GetById(id);
            if (messageValue.IsRead == false)
            {
                messageValue.IsRead = true;
                mm.MessageUpdate(messageValue);
            }
            return View(messageValue);
        }

        public ActionResult GetSendboxMessageDetails(int id)
        {
            var messageValue = mm.GetById(id);
            if (messageValue.IsRead == false)
            {
                messageValue.IsRead = true;
                mm.MessageUpdate(messageValue);
            }
            return View(messageValue);
        }
    }
}

MVC_Camp/Views/Draft/GetMessageDetails.cshtml
@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model EntityLayer.Concrete.DraftMessage
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Send A New Message</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Compose</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("ContactLeftPart", "Contact")
                <!-- /.col -->
                <div class="col-md-9">
                    @using (Html.BeginForm("NewMessage", "Message", FormMethod.Post))
                    {
                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Compose New Message</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.Label("Receiver Mail")
                                    @Html.TextBoxFor(x => x.ReceiverMail, new { @class = "form-control", @placeholder = "Receiver Mail" })
                                    @Html.ValidationMessageFor(x => x.ReceiverMail, null, new { @class = "text-red" })
                                </div>
                                <div class="form-group">
                                    @Html.Label("Subject")
                                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control", @placeholder = "Enter the subject" })
                                    @Html.ValidationMessageFor(x => x.Subject, null, new { @class = "text-red" })
                                </div>
                                <div class="form-group">
                                    @Html.Label("Add Your Message")
                                    @Html.TextAreaFor(x => x.MessageContent, new { @class = "form-control", @id = "compose-textarea" })
                                    @Html.ValidationMessageFor(x => x.MessageContent, null, new { @class = "text-red" })
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Attachment
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">
                                    <button type="submit" name="button" value="draft" class="btn btn-default"><i class="fas fa-pencil-alt"></i>Draft</button>
                                    <button type="submit" name="button" value="send" class="btn btn-primary"><i class="far fa-envelope"></i>Send</button>
                                </div>
                                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> Discard</button>
                            </div>
                            <!-- /.card-footer -->
                        </div>
                    }
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</body>
</html>

MVC_Camp/Views/Draft/Index.cshtml
@using EntityLayer.Concrete
@model List<DraftMessage>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

<!-- Content Wrapper. Contains page content -->

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Personal Message Box</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Inbox</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                @Html.Action("ContactLeftPart", "Contact")
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Inbox</h3>
                            <div class="card-tools">
                                <div class="input-group input-group-sm">
                                    <input type="text" class="form-control" placeholder="Search Mail">
                                    <div class="input-group-append">
                                        <div class="btn btn-primary">
                                            <i class="fas fa-search"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-tools -->
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-controls">
                                <!-- Check all button -->
                                <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                    <i class="far fa-square"></i>
                                </button>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                                </div>
                                <!-- /.btn-group -->
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                                <div class="float-right">
                                    1-50/@Model.Count()
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                    </div>
                                    <!-- /.btn-group -->
                                </div>
                                <!-- /.float-right -->
                            </div>
                            <div class="table-responsive mailbox-messages">
                                <table class="table table-hover table-striped">
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            var length = item.MessageContent.Length < 30 ? item.MessageContent.Length : 30;
                                            <tr>
                                                <td>
                                                    <div class="icheck-primary">
                                                        <input type="checkbox" value="" id="check1">
                                                        <label for="check1"></label>
                                                    </div>
                                                </td>
                                                <td id="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>
                                                <td class="mailbox-name"><a href="/Draft/GetMessageDetails/@item.Id">To: @item.ReceiverMail</a></td>
                                                <td class="mailbox-subject">
                                                    <b>@item.Subject</b> - @item.MessageContent.Substring(0, @length)...
                                                </td>
                                                <td class="mailbox-attachment"></td>
                                                <td class="mailbox-date">@item.SentDate.ToString("dd/MM/yyyy")</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                                <!-- /.table -->
                            </div>
                            <!-- /.mail-box-messages -->
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer p-0">
                            <div class="mailbox-controls">
                                <!-- Check all button -->
                                <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                    <i class="far fa-square"></i>
                                </button>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                                </div>
                                <!-- /.btn-group -->
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                                <div class="float-right">
                                    1-50/@Model.Count()
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                        <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                    </div>
                                    <!-- /.btn-group -->
                                </div>
                                <!-- /.float-right -->
                            </div>
                        </div>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
    </section>

    <script>
        $(function () {
            $('#mailbox-star').click(function (e) {
                e.preventDefault();
                console.log(1);
                //detect type
                var $this = $(this).find('a > i')
                var glyph = $this.hasClass('glyphicon')
                var fa = $this.hasClass('fa')

                //Switch states
                if (glyph) {
                    $this.toggleClass('glyphicon-star')
                    $this.toggleClass('glyphicon-star-empty')
                }

                if (fa) {
                    $this.toggleClass('fa-star')
                    $this.toggleClass('fa-star-o')
                }
            });
        })
    </script>

</body>
</html>