MVC_Camp/Controllers/TestimonialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;

namespace MVC_Camp.Controllers
{
    public class TestimonialController : Controller
    {
        private TestimonialManager tm = new TestimonialManager(new EfTestimonialDal());
        public ActionResult Index()
        {
            var values = tm.GetList();
            return View(values);
        }

        public ActionResult UpdateTestimonial(int id)
        {
            var testimonial = tm.GetById(id);
            switch (testimonial.Approved)
            {
                case true:
                    testimonial.Approved = false;
                    break;
                case false:
                    testimonial.Approved = true;
                    break;

            }
            tm.TestimonialUpdate(testimonial);
            return RedirectToAction("Index");
        }

        public ActionResult AddTestimonial()
        {
            return View();
        }
    }
}

MVC_Camp/Controllers/WriterPanelController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;


namespace MVC_Camp.Controllers
{
    public class WriterPanelController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterValidator writerValidator = new WriterValidator();
        private WriterManager wm = new WriterManager(new EfWriterDal());
        private TestimonialManager tm = new TestimonialManager(new EfTestimonialDal());
        TestimonialValidator testimonialValidator = new TestimonialValidator();


        public ActionResult MyProfile()
        {
            string p = (string)Session["WriterMail"];
            var id = wm.GetWriterId(p);
            var writerValue = wm.GetById(id);
            return View(writerValue);
        }

        [HttpGet]
        public ActionResult WriterProfile()
        {
            string p = (string)Session["WriterMail"];
            var id = wm.GetWriterId(p);
            var writerValue = wm.GetById(id);
            return View(writerValue);
        }

        [HttpPost]
        public ActionResult WriterProfile(Writer writer)
        {

            ValidationResult results = writerValidator.Validate(writer);
            if (results.IsValid)
            {
                wm.UpdateWriter(writer);
                return RedirectToAction("AllHeadings");
            }
            else
            {
                foreach (var error in results.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult MyHeadings(String p)
        {
            p = (string)Session["WriterMail"];
            var writeridinfo = wm.GetWriterId(p);
            var values = hm.GetListByWriter(writeridinfo);
            return View(values);
        }

        [HttpGet]
        public ActionResult NewHeading()
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                                                  select new SelectListItem()
                                                  {
                                                      Value = x.CategoryId.ToString(),
                                                      Text = x.CategoryName,
                                                  }).ToList();

            ViewBag.vlc = valuecategory;


            return View();
        }

        [HttpPost]
        public ActionResult NewHeading(Heading heading)
        {
            string Writermail = (string)Session["WriterMail"];
            heading.HeadingCreateDateTime = DateTime.Parse(DateTime.Now.ToShortDateString());
            heading.HeadingStatus = true;
            heading.WriterId = wm.GetWriterId(Writermail);
            hm.HeadingAdd(heading);
            return RedirectToAction("MyHeadings");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                                                  select new SelectListItem()
                                                  {
                                                      Value = x.CategoryId.ToString(),
                                                      Text = x.CategoryName,
                                                  }).ToList();

            ViewBag.vlc = valuecategory;

            var HeadingValue = hm.GetById(id);
            return View(HeadingValue);
        }

        [HttpPost]
        public ActionResult EditHeading(Heading heading)
        {
            heading.HeadingStatus = true;
            hm.UpdateHeading(heading);
            return RedirectToAction("MyHeadings");
        }

        public ActionResult DeleteHeading(int id)
        {
            var headingValue = hm.GetById(id);
            switch (headingValue.HeadingStatus)
            {
                case true:
                    headingValue.HeadingStatus = false;
                    break;
                case false:
                    headingValue.HeadingStatus = true;
                    break;

            }
            hm.DeleteHeading(headingValue);
            return RedirectToAction("MyHeadings");
        }

        public ActionResult AllHeadings(int page = 1)
        {
            var headings = hm.GetList().ToPagedList(page, 4);
            return View(headings);
        }

        public ActionResult Testimonial()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Testimonial(Testimonial p)
        {
            ValidationResult results = testimonialValidator.Validate(p);
            if (results.IsValid)
            {
                var mail = (string)Session["WriterMail"];
                var writer = wm.GetByMail(mail);

                p.Name = writer.WriterName + " " + writer.WriterLastname;
                p.Date = DateTime.Now;
                tm.TestimonialAddBl(p);
                return RedirectToAction("MyProfile");
            }
            else
            {
                foreach (var error in results.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }

            return View();
        }
    }
}

MVC_Camp/Views/WriterPanel/AllHeadings.cshtml
@using EntityLayer.Concrete
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Heading>
@{
    ViewBag.Title = "AllHeadings";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@{ string color = "";}

<br />
<h2>All Headings</h2>

<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Heading Operations</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th style="width: 20%">
                            Heading Name
                        </th>
                        <th style="width: 20%">
                            Created By
                        </th>
                        <th style="width: 10%" class="text-center">
                            Category
                        </th>
                        <th style="width: 30%">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        if (item.Category.CategoryName == "Theater")
                        {
                            color = "badge badge-warning";
                        }

                        if (item.Category.CategoryName == "Education")
                        {
                            color = "badge badge-success";
                        }
                        if (item.Category.CategoryName == "Development")
                        {
                            color = "badge badge-info";
                        }
                        if (item.Category.CategoryName == "Series")
                        {
                            color = "badge badge-secondary";
                        }
                        if (item.Category.CategoryName == "Movies")
                        {
                            color = "badge badge-danger";
                        }

                        if (item.Category.CategoryName == "Sport")
                        {
                            color = "badge badge-dark";
                        }

                        <tr>
                            <th>
                                @item.HeadingId
                            </th>
                            <td>
                                <a>
                                    @item.HeadingName
                                </a>
                                <br />
                                <small>
                                    Created @item.HeadingCreateDateTime.ToString("D")
                                </small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                    </li>
                                </ul>
                            </td>
                            <td class="project-state">
                                <span class="@color">@item.Category.CategoryName</span>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" target="_blank" href="/Default/Headings/@item.HeadingId">
                                    <i class="fas fa-folder">
                                    </i>
                                    Contents
                                </a>
                                <a class="btn btn-info btn-sm" href="/WriterPanelContent/AddContent/@item.HeadingId">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Add Content
                                </a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</section>
<div style="float: right">

    @Html.PagedListPager((IPagedList)Model, page => Url.Action("AllHeadings", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
{
    //LiElementClasses = new List<string>() { "page-link" },
    LinkToFirstPageFormat = "<<",
    LinkToPreviousPageFormat = "<",
    LinkToNextPageFormat = ">",
    LinkToLastPageFormat = ">>",
    DisplayLinkToFirstPage = PagedListDisplayMode.Always,
    DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
    DisplayLinkToLastPage = PagedListDisplayMode.Always,
    DisplayLinkToNextPage = PagedListDisplayMode.Always,
    //MaximumPageNumbersToDisplay = 0,
    DisplayEllipsesWhenNotShowingAllPageNumbers = false,
}, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "some_grid_container" }))
    @*new PagedListRenderOptions
        {
            LiElementClasses = new List<string>
            {
                "page-link"
            }
        })*@
</div>

MVC_Camp/Views/WriterPanel/EditHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>Heading Updating Page</h2>
@using (Html.BeginForm("EditHeading", "WriterPanel", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.HeadingId)
    @Html.HiddenFor(x => x.HeadingCreateDateTime)
    @Html.HiddenFor(x => x.WriterId)
    @Html.Label("Heading Name")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    <br />
    @Html.Label("Heading Category")
    @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Update</button>
</div>
}

MVC_Camp/Views/WriterPanel/MyHeadings.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "MyHeadings";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
@{ string color = "";}
@{ string status = "";}
@{ string btnName = "";}
@{string btnClass = "";}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Projects</h1>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Heading Operations</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th style="width: 20%">
                            Heading Name
                        </th>
                        <th style="width: 20%">
                            Created By
                        </th>
                        <th style="width: 10%" class="text-center">
                            Category
                        </th>
                        <th style="width: 30%">
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        if (item.Category.CategoryName == "Theater")
                        {
                            color = "badge badge-warning";
                        }

                        if (item.Category.CategoryName == "Education")
                        {
                            color = "badge badge-success";
                        }
                        if (item.Category.CategoryName == "Development")
                        {
                            color = "badge badge-info";
                        }
                        if (item.Category.CategoryName == "Series")
                        {
                            color = "badge badge-secondary";
                        }
                        if (item.Category.CategoryName == "Movies")
                        {
                            color = "badge badge-danger";
                        }

                        if (item.Category.CategoryName == "Sport")
                        {
                            color = "badge badge-dark";
                        }
                        switch (item.HeadingStatus)
                        {
                            case true:
                                status = "badge badge-success";
                                btnName = "Make Passive";
                                btnClass = "btn btn-danger btn-sm";
                                break;
                            case false:
                                status = "badge badge-danger";
                                btnName = "Make Active";
                                btnClass = "btn btn-success btn-sm";
                                break;
                        }

                        <tr>
                            <th>
                                @item.HeadingId
                            </th>
                            <td>
                                <a>
                                    @item.HeadingName
                                </a>
                                <br />
                                <small>
                                    Created @item.HeadingCreateDateTime.ToString("D")
                                </small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                    </li>
                                </ul>
                            </td>
                            <td class="project-state">
                                <span class="@color">@item.Category.CategoryName</span>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="/WriterPanel/ContentByHeading/@item.HeadingId">
                                    <i class="fas fa-folder">
                                    </i>
                                    Contents
                                </a>
                                <a class="btn btn-info btn-sm" href="/WriterPanel/EditHeading/@item.HeadingId">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Update
                                </a>
                                <a class="@btnClass" href="/WriterPanel/DeleteHeading/@item.HeadingId">
                                    <i class="fas fa-trash">
                                    </i>
                                    @btnName
                                </a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
    <a href="/WriterPanel/NewHeading" class="btn btn-primary">Add a new Heading</a>
</section>

MVC_Camp/Views/WriterPanel/NewHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "NewHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<br />
<h2>Add New Heading </h2>
<br />

@using (Html.BeginForm("NewHeading", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Heading Name")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Heading Category")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryId)
        <br />
        <button class="btn btn-info">Add Heading</button>
    </div>
}

MVC_Camp/Views/WriterPanel/Testimonial.cshtml
@model EntityLayer.Concrete.Testimonial

@{
    ViewBag.Title = "Testimonial";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<br />
<h2>Testimonials</h2>

@using (Html.BeginForm("Testimonial", "WriterPanel", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Testimonial Content")
    @Html.TextAreaFor(x => x.TestimonialContent, new { @class = "form-control" })
    <br />
    @Html.ValidationMessageFor(x => x.TestimonialContent, null)
    <br /><br />
    <button class="btn btn-info">Add Testimonial</button>
</div>
}

MVC_Camp/Views/WriterPanel/WriterProfile.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "Update Profile";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}



<br />
<h2>Edit Your Profile</h2>
<br />
@using (Html.BeginForm("WriterProfile", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.WriterId, new { @class = "form-control" })
        @Html.Label("Writer Name")
        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterName, null, new { @class="text-danger"})
        <br />
        @Html.Label("Writer Last Name")
        @Html.TextBoxFor(x => x.WriterLastname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterLastname, null, new { @class = "text-danger" })
        <br />
        @Html.Label("Writer Mail")
        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterMail, null, new { @class = "text-danger" })
        <br />
        @Html.Label("Writer Password")
        @Html.TextBoxFor(x => x.WriterPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterPassword, null, new { @class = "text-danger" })
        <br />
        @Html.Label("Writer Image Link")
        @Html.TextBoxFor(x => x.WriterImage, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterImage, null, new { @class = "text-danger" })
        <br />
        @Html.Label("Writer Title")
        @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout, null, new { @class = "text-danger" })
        <br />
        @Html.Label("Writer About")
        @Html.TextBoxFor(x => x.WriterAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.WriterAbout, null, new { @class = "text-danger" })
        <br />
        <button class="btn btn-info">Save Changes</button>
    </div>
}